### PR TITLE
added gps part numbers and built the interfaces for the OutputMixing and SendInstructionsToSafety modules

### PR DESCRIPTION
**Pull request by Fberbari**

### CODE REVIEW

**Review by heyitslu — COMMENTED** [review]
No typos - everything looks good!

**Comment by Fberbari** [comment]
I'll change the name of the sendToActuators module before this gets merged.

**Comment by Fberbari** [comment]
Name has been changed.

**Comment by avlepage** [comment]
Looks good, builds 👍

**Review by avlepage — APPROVED** [review]
Looks good to me and builds fine!

**Comment by avlepage** [comment]
@heyitslu I think you might need to re-approve

**Review by heyitslu — COMMENTED** [review]
All good!

**Review by heyitslu — APPROVED** [review]

**Pull request merged**
